// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4oWS0DBLBKV2BxAi9Vc28nICSlQdp_bM',
    appId: '1:610548128900:web:49661b32a2a6c955cb76d1',
    messagingSenderId: '610548128900',
    projectId: 'kisiden-projesi',
    authDomain: 'kisiden-projesi.firebaseapp.com',
    storageBucket: 'kisiden-projesi.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKWCsCKDWoG2LZfU1VyXwOYGSCztF0td4',
    appId: '1:610548128900:android:5ceeb1099ae3c9c4cb76d1',
    messagingSenderId: '610548128900',
    projectId: 'kisiden-projesi',
    storageBucket: 'kisiden-projesi.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPApBpQRZHkHowuBfh-fD6O8IgHMvQfJw',
    appId: '1:610548128900:ios:c373af029eaad5a8cb76d1',
    messagingSenderId: '610548128900',
    projectId: 'kisiden-projesi',
    storageBucket: 'kisiden-projesi.firebasestorage.app',
    androidClientId:
        '610548128900-tgkl7jlr8s5r4juqkfsp736dt277kdoa.apps.googleusercontent.com',
    iosClientId:
        '610548128900-u2qp6usl106q2iq2achqh49nrbctu8fo.apps.googleusercontent.com',
    iosBundleId: 'com.kisiden.appim',
  );
}
